spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/coupon_example
    username: app
    password: password

# kafka
kafka:
  bootstrap-address: localhost:29092,localhost:39092